### ISSUE TITLE
InvalidRequirement: Invalid URL given while installing requirements.txt

### ISSUE THREAD

**Issue by Phil-Reck** [uonafya/dslminer#2]
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3101, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/_vendor/packaging/requirements.py", line 101, in __init__
    raise InvalidRequirement("Invalid URL given")
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid URL given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phil/projects/work/dslminer/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/phil/projects/work/dslminer/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/home/phil/projects/work/dslminer/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 358, in run
    requirement_set = resolver.resolve(
  File "/home/phil/projects/work/dslminer/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 179, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/phil/projects/work/dslminer/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/phil/projects/work/dslminer/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 305, in _get_abstract_dist_for
    skip_reason = self._check_skip_installed(req)
  File "/home/phil/projects/work/dslminer/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 232, in _check_skip_installed
    req_to_install.check_if_exists(self.use_user_site)
  File "/home/phil/projects/work/dslminer/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 430, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 479, in get_distribution
    dist = Requirement.parse(dist)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3148, in parse
    req, = parse_requirements(s)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3094, in parse_requirements
    yield Requirement(line)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid URL given

**Comment by Phil-Reck** [comment]
Sorted that out, changed 
pyflux @ file:///home/duncanndiithi/PycharmProjects/dslminer/pyflux version in requirements.txt to it's latest version == 0.4.15
